/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entity.Kelime;
import entity.Resim;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Batu
 */
public class MainFrame extends javax.swing.JFrame {

    int acilanharf = 0;
    Kelime kelime;
    int puan = 50;
    ArrayList<Character> harfler;
    ArrayList<Character> verilenharfler;

    public MainFrame() {
        initComponents();
        lblPuan.setText(Integer.toString(puan));
    }

    private void temizle() {
        lblSonuc.setText("");
        txtKelime.setText("");
    }

    public void puanKontrol(String durum) {
        switch (durum) {
            case "dogru":
                puan += (kelime.getIcerik().length() - acilanharf) * 3;
                break;
            case "yanlis":
                puan += -3;
                break;
            case "harf":
                puan += -10;
                break;
            case "pas":
                puan += -5;
                break;
        }
        if (puan < 0) {
            lblPuan.setText(Integer.toString(puan));
            showMessageDialog(null, "- puana düştünüz oyun baştan başlıyor...");
            temizle();
            kelimeResimHazirla();
            puan = 50;
        }
        lblPuan.setText(Integer.toString(puan));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rsm1 = new javax.swing.JLabel();
        rsm3 = new javax.swing.JLabel();
        rsm2 = new javax.swing.JLabel();
        rsm4 = new javax.swing.JLabel();
        lblKelime = new javax.swing.JLabel();
        btnGonder = new javax.swing.JButton();
        btnPas = new javax.swing.JButton();
        btnHarf = new javax.swing.JButton();
        lblPuanBaslik = new javax.swing.JLabel();
        lblPuan = new javax.swing.JLabel();
        txtKelime = new javax.swing.JTextField();
        lblSonuc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        rsm1.setText("rsm1");
        rsm1.setToolTipText("");
        rsm1.setMaximumSize(new java.awt.Dimension(300, 200));
        rsm1.setMinimumSize(new java.awt.Dimension(300, 200));

        rsm3.setText("rsm3");
        rsm3.setToolTipText("");
        rsm3.setMaximumSize(new java.awt.Dimension(300, 200));
        rsm3.setMinimumSize(new java.awt.Dimension(300, 200));

        rsm2.setText("rsm2");
        rsm2.setToolTipText("");
        rsm2.setMaximumSize(new java.awt.Dimension(300, 200));

        rsm4.setText("rsm4");
        rsm4.setToolTipText("");
        rsm4.setMaximumSize(new java.awt.Dimension(300, 200));
        rsm4.setMinimumSize(new java.awt.Dimension(300, 200));

        lblKelime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblKelime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKelime.setText("Kelime");
        lblKelime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnGonder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGonder.setText("DENE");
        btnGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGonderActionPerformed(evt);
            }
        });

        btnPas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPas.setText("PAS");
        btnPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasActionPerformed(evt);
            }
        });

        btnHarf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHarf.setText("HARF AL");
        btnHarf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarfActionPerformed(evt);
            }
        });

        lblPuanBaslik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPuanBaslik.setText("Puan");

        lblPuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuan.setText("0");
        lblPuan.setToolTipText("");
        lblPuan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtKelime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtKelime.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblSonuc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSonuc.setForeground(new java.awt.Color(255, 0, 0));
        lblSonuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenu1.setText("Skorlar");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayarlar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPuanBaslik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(292, 292, 292))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rsm3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rsm1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblKelime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHarf)))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rsm4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rsm2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGonder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSonuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPuanBaslik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuan)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rsm1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rsm3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rsm2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rsm4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSonuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHarf)
                        .addComponent(btnPas)
                        .addComponent(btnGonder)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelime)
                    .addComponent(txtKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void kelimeResimHazirla() {
        try {
            acilanharf = 0;
            harfler = new ArrayList<Character>();
            verilenharfler = new ArrayList<Character>();
            temizle();
            String cizgi = "";
            Kontrol kntr = new Kontrol();
            ArrayList<ImageIcon> imageList = new ArrayList<ImageIcon>();
            ArrayList<JLabel> rsmler = new ArrayList<JLabel>();
            rsmler.add(rsm1);
            rsmler.add(rsm2);
            rsmler.add(rsm3);
            rsmler.add(rsm4);

            kelime = dao.KelimeDAO.rastgeleKelimeGetir();
            ArrayList<Resim> resimler = dao.ResimDAO.kelimeResimleriniGetir(kelime);
            imageList = kntr.blobToImageList(resimler);
            for (int i = 0; i < imageList.size(); i++) {
                rsmler.get(i).setIcon(imageList.get(i));
            }

            for (int s = 0; s < kelime.getIcerik().length(); s++) {
                char a = kelime.getIcerik().charAt(s);
                harfler.add(a);
                cizgi += "_ ";
                verilenharfler.add('_');
            }
            lblKelime.setText(cizgi);
        } catch (Exception ex) {
            System.out.print("Resim hata-kelime" + ex);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        kelimeResimHazirla();
    }//GEN-LAST:event_formWindowOpened

    private void btnPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasActionPerformed
        puanKontrol("pas");
        kelimeResimHazirla();
    }//GEN-LAST:event_btnPasActionPerformed

    private void btnGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGonderActionPerformed
        Kontrol kntr = new Kontrol();
        if (kntr.kelimeKontrol(txtKelime.getText(), kelime)) {
            puanKontrol("dogru");
            kelimeResimHazirla();
        } else {
            puanKontrol("yanlis");
            lblSonuc.setText("Tahmininiz Yanlış");
        }
    }//GEN-LAST:event_btnGonderActionPerformed

    private void btnHarfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarfActionPerformed

        if (puan >= 10 && (kelime.getIcerik().length() - acilanharf) > 1) {
            acilanharf += 1;
            puanKontrol("harf");
            String kelime = "";
            Random rnd = new Random();
            int harfindex = rnd.nextInt(harfler.size());
            char harf = harfler.get(harfindex);
            while (verilenharfler.indexOf(harf) == harfindex) {
                harfindex = rnd.nextInt(harfler.size());
                harf = harfler.get(harfindex);
            }
            verilenharfler.set(harfindex, harf);
            for (int i = 0; i < verilenharfler.size(); i++) {
                kelime += verilenharfler.get(i) + " ";
            }
            lblKelime.setText(kelime);
        } else {
            showMessageDialog(null, "Kelimeye ait harf açma sınırını doldurdunuz , veya yeterli puanınız yok...");
          
        }
    }//GEN-LAST:event_btnHarfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGonder;
    private javax.swing.JButton btnHarf;
    private javax.swing.JButton btnPas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblKelime;
    private javax.swing.JLabel lblPuan;
    private javax.swing.JLabel lblPuanBaslik;
    private javax.swing.JLabel lblSonuc;
    private javax.swing.JLabel rsm1;
    private javax.swing.JLabel rsm2;
    private javax.swing.JLabel rsm3;
    private javax.swing.JLabel rsm4;
    private javax.swing.JTextField txtKelime;
    // End of variables declaration//GEN-END:variables
}
